export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const FETCH_IMAGE_CLASS_SUCCESS = 'FETCH_IMAGE_CLASS_SUCCESS';
export const FACEBOOK_LOGIN_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const CLEAN_LOGIN_DATA = 'CLEAN_LOGIN_DATA';
