export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const FETCH_IMAGE_CLASS_SUCCESS = 'FETCH_IMAGE_CLASS_SUCCESS';
export const FACEBOOK_LOGIN_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const CLEAN_LOGIN_DATA = 'CLEAN_LOGIN_DATA';
export const FETCH_DATA_IN_PROGRESS = 'FETCH_DATA_IN_PROGRESS';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const CLEANUP_DATA = 'CLEAN_UP_DATA';
